@host = http://localhost:5259/scalar

### Test API
GET {{host}}/weatherforecast/
Accept: application/json

### Register user
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "username": "Leon",
  "email": "leon@test.com",
  "password": "123456"
}